services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=alinfo
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT} # Expose MySQL port for external connections
    volumes:
      - db:/var/lib/mysql
    networks:
      - projectdevops

  appspring:
    depends_on:
      - mysqldb
    image: oussema619/tp_achat_devops:${APP_VERSION} # Use dynamic tag
    container_name: springapp
    restart: on-failure
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/alinfo?useSSL=false",
        "spring.datasource.username" : "${MYSQLDB_USER}",
        "spring.datasource.password" : "${MYSQLDB_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL57Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - projectdevops

volumes:
  db:

networks:
  projectdevops:
